CC = g++



btree.o: global.h btree.h btree.cc buffer.o 
	$(CC) -c btree.cc
buffer.o: global.h buffer.h buffer.cc
	$(CC) -c buffer.cc
MiniSQL.o: global.h MiniSQL.h MiniSQL.cc buffer.o btree.o record.o catalog.o
	$(CC) -c MiniSQL.cc